[package]
name = "transaction_engine"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
rust_decimal = { version = "1.39", features = ["macros"] }
anyhow = "1.0"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }